// <auto-generated />
using System;
using GridSign.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GridSign.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251110113526_EmailVerificationFields")]
    partial class EmailVerificationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GridSign.Models.Entities.EnvelopeLog", b =>
                {
                    b.Property<int>("EnvelopeLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EnvelopeLogId"));

                    b.Property<int>("EnvelopeId")
                        .HasColumnType("int");

                    b.Property<string>("PerformedAction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("EnvelopeLogId");

                    b.ToTable("EnvelopeLog");
                });

            modelBuilder.Entity("GridSign.Models.Entities.Field", b =>
                {
                    b.Property<int>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FieldId"));

                    b.Property<int?>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FieldPosition")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("FieldId");

                    b.HasIndex("DocumentId");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("GridSign.Models.Entities.FileResource", b =>
                {
                    b.Property<int>("FileResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FileResourceId"));

                    b.Property<byte[]>("ResourceData")
                        .HasColumnType("MEDIUMBLOB");

                    b.Property<string>("ResourceName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("FileResourceId");

                    b.ToTable("FileResources");
                });

            modelBuilder.Entity("GridSign.Models.Entities.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GdFileId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Img")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ImageId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("GridSign.Models.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GridSign.Models.Entities.SignedDocumentVersion", b =>
                {
                    b.Property<int>("SignedDocumentVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SignedDocumentVersionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FileResourceId")
                        .HasColumnType("int");

                    b.Property<int>("SignedDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("SignedDocumentVersionId");

                    b.HasIndex("FileResourceId");

                    b.HasIndex("SignedDocumentId");

                    b.ToTable("SignedDocumentVersion");
                });

            modelBuilder.Entity("GridSign.Models.Entities.Template", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsSequentialSigningEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TemplateName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("TemplateOwner")
                        .HasMaxLength(255)
                        .HasColumnType("char(255)");

                    b.HasKey("TemplateId");

                    b.HasIndex("TemplateOwner");

                    b.ToTable("Template");
                });

            modelBuilder.Entity("GridSign.Models.Entities.TemplateDocument", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("DocumentId");

                    b.HasIndex("TemplateId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("GridSign.Models.Entities.TemplateDocumentFiles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int>("FileResourceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("FileResourceId");

                    b.ToTable("DocumentAttachments");
                });

            modelBuilder.Entity("GridSign.Models.Entities.TemplateRecipient", b =>
                {
                    b.Property<int>("TemplateRecipientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TemplateRecipientId"));

                    b.Property<Guid?>("DefaultUserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("DeliveryType")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RecipientRoleId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateDocumentId")
                        .HasColumnType("int");

                    b.HasKey("TemplateRecipientId");

                    b.HasIndex("DefaultUserId");

                    b.HasIndex("RecipientRoleId");

                    b.HasIndex("TemplateDocumentId");

                    b.ToTable("TemplateRecipient");
                });

            modelBuilder.Entity("GridSign.Models.Entities.TemplateRecipientField", b =>
                {
                    b.Property<int>("RecipientFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RecipientFieldId"));

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCommonField")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int");

                    b.HasKey("RecipientFieldId");

                    b.HasIndex("FieldId");

                    b.HasIndex("RecipientId");

                    b.ToTable("TemplateRecipientFields");
                });

            modelBuilder.Entity("GridSign.Models.Entities.TemplateRecipientRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RolePriority")
                        .HasColumnType("int");

                    b.HasKey("RoleId");

                    b.ToTable("RecipientRole");
                });

            modelBuilder.Entity("GridSign.Models.Entities.Users", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Company")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsMailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PendingEmail")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ProfilePicId")
                        .HasColumnType("int");

                    b.Property<string>("UserRole")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("ProfilePicId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GridSign.Models.Entities.Verification", b =>
                {
                    b.Property<int>("VerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VerificationId"));

                    b.Property<bool>("IsAlreadyUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ValidTill")
                        .HasColumnType("datetime(6)");

                    b.HasKey("VerificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Verification");
                });

            modelBuilder.Entity("GridSign.Models.Entities.Workflow", b =>
                {
                    b.Property<int>("WorkFlowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WorkFlowId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RecipientConfiguration")
                        .HasColumnType("int");

                    b.Property<int>("ReminderIntervalInDays")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ValidUntil")
                        .HasColumnType("date");

                    b.Property<Guid>("WorkFlowCreator")
                        .HasColumnType("char(36)");

                    b.Property<string>("WorkflowName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("WorkFlowId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("WorkFlowCreator");

                    b.ToTable("Workflow");
                });

            modelBuilder.Entity("GridSign.Models.Entities.WorkflowEnvelope", b =>
                {
                    b.Property<int>("WorkflowEnvelopeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WorkflowEnvelopeId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("WorkflowEnvelopeId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("WorkflowEnvelope");
                });

            modelBuilder.Entity("GridSign.Models.Entities.WorkflowRecipient", b =>
                {
                    b.Property<int>("WorkflowRecipientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WorkflowRecipientId"));

                    b.Property<Guid?>("CustomUser")
                        .HasColumnType("char(36)");

                    b.Property<int>("EmailStatus")
                        .HasColumnType("int");

                    b.Property<int>("EnvelopeId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateRecipientId")
                        .HasColumnType("int");

                    b.Property<bool>("UseDefaultUser")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("WorkflowRecipientId");

                    b.HasIndex("CustomUser");

                    b.HasIndex("EnvelopeId")
                        .IsUnique();

                    b.HasIndex("TemplateRecipientId");

                    b.ToTable("WorkflowRecipient");
                });

            modelBuilder.Entity("GridSign.Models.Entities.WorkflowRecipientSignature", b =>
                {
                    b.Property<int>("RecipientSignatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RecipientSignatureId"));

                    b.Property<bool>("IsSigned")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RecipientSignedDocumentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WorkflowRecipientId")
                        .HasColumnType("int");

                    b.HasKey("RecipientSignatureId");

                    b.HasIndex("RecipientSignedDocumentId");

                    b.HasIndex("WorkflowRecipientId");

                    b.ToTable("WorkflowRecipientSignature");
                });

            modelBuilder.Entity("GridSign.Models.Entities.WorkflowRecipientSignedDocument", b =>
                {
                    b.Property<int>("SignedDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SignedDocumentId"));

                    b.Property<bool>("IsSharedDocument")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("SignedDocumentId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("WorkflowRecipientSignedDocument");
                });

            modelBuilder.Entity("GridSign.Models.Entities.WorkflowSignatureProof", b =>
                {
                    b.Property<int>("SignatureProofId")
                        .HasColumnType("int");

                    b.Property<int>("FileResourceId")
                        .HasColumnType("int");

                    b.HasKey("SignatureProofId");

                    b.HasIndex("FileResourceId");

                    b.ToTable("SignatureProof");
                });

            modelBuilder.Entity("GridSign.Models.Entities.Field", b =>
                {
                    b.HasOne("GridSign.Models.Entities.TemplateDocument", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("GridSign.Models.Entities.Notification", b =>
                {
                    b.HasOne("GridSign.Models.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GridSign.Models.Entities.SignedDocumentVersion", b =>
                {
                    b.HasOne("GridSign.Models.Entities.FileResource", "FileResource")
                        .WithMany()
                        .HasForeignKey("FileResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GridSign.Models.Entities.WorkflowRecipientSignedDocument", "WorkflowRecipientSignedDocument")
                        .WithMany("SignedDocumentVersions")
                        .HasForeignKey("SignedDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileResource");

                    b.Navigation("WorkflowRecipientSignedDocument");
                });

            modelBuilder.Entity("GridSign.Models.Entities.Template", b =>
                {
                    b.HasOne("GridSign.Models.Entities.Users", "Users")
                        .WithMany()
                        .HasForeignKey("TemplateOwner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("GridSign.Models.Entities.TemplateDocument", b =>
                {
                    b.HasOne("GridSign.Models.Entities.Template", "Template")
                        .WithMany("Documents")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("GridSign.Models.Entities.TemplateDocumentFiles", b =>
                {
                    b.HasOne("GridSign.Models.Entities.TemplateDocument", "Document")
                        .WithMany("TemplateDocumentFiles")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GridSign.Models.Entities.FileResource", "File")
                        .WithMany()
                        .HasForeignKey("FileResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("File");
                });

            modelBuilder.Entity("GridSign.Models.Entities.TemplateRecipient", b =>
                {
                    b.HasOne("GridSign.Models.Entities.Users", "DefaultUser")
                        .WithMany()
                        .HasForeignKey("DefaultUserId");

                    b.HasOne("GridSign.Models.Entities.TemplateRecipientRole", "RecipientRole")
                        .WithMany()
                        .HasForeignKey("RecipientRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GridSign.Models.Entities.TemplateDocument", "TemplateDocument")
                        .WithMany("TemplateRecipients")
                        .HasForeignKey("TemplateDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultUser");

                    b.Navigation("RecipientRole");

                    b.Navigation("TemplateDocument");
                });

            modelBuilder.Entity("GridSign.Models.Entities.TemplateRecipientField", b =>
                {
                    b.HasOne("GridSign.Models.Entities.Field", "Field")
                        .WithMany("RecipientFields")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GridSign.Models.Entities.TemplateRecipient", "TemplateRecipient")
                        .WithMany("TemplateRecipientField")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("TemplateRecipient");
                });

            modelBuilder.Entity("GridSign.Models.Entities.Users", b =>
                {
                    b.HasOne("GridSign.Models.Entities.FileResource", "FileResource")
                        .WithOne("UploadedBy")
                        .HasForeignKey("GridSign.Models.Entities.Users", "ProfilePicId");

                    b.Navigation("FileResource");
                });

            modelBuilder.Entity("GridSign.Models.Entities.Verification", b =>
                {
                    b.HasOne("GridSign.Models.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GridSign.Models.Entities.Workflow", b =>
                {
                    b.HasOne("GridSign.Models.Entities.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GridSign.Models.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("WorkFlowCreator")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GridSign.Models.Entities.WorkflowEnvelope", b =>
                {
                    b.HasOne("GridSign.Models.Entities.Workflow", "Workflow")
                        .WithMany("WorkflowEnvelopes")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("GridSign.Models.Entities.WorkflowRecipient", b =>
                {
                    b.HasOne("GridSign.Models.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("CustomUser");

                    b.HasOne("GridSign.Models.Entities.WorkflowEnvelope", "WorkflowEnvelope")
                        .WithOne("WorkflowRecipient")
                        .HasForeignKey("GridSign.Models.Entities.WorkflowRecipient", "EnvelopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GridSign.Models.Entities.TemplateRecipient", "TemplateRecipient")
                        .WithMany()
                        .HasForeignKey("TemplateRecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateRecipient");

                    b.Navigation("User");

                    b.Navigation("WorkflowEnvelope");
                });

            modelBuilder.Entity("GridSign.Models.Entities.WorkflowRecipientSignature", b =>
                {
                    b.HasOne("GridSign.Models.Entities.WorkflowRecipientSignedDocument", "WorkflowRecipientSignedDocument")
                        .WithMany("Signatures")
                        .HasForeignKey("RecipientSignedDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GridSign.Models.Entities.WorkflowRecipient", "WorkflowRecipient")
                        .WithMany("RecipientSignatures")
                        .HasForeignKey("WorkflowRecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowRecipient");

                    b.Navigation("WorkflowRecipientSignedDocument");
                });

            modelBuilder.Entity("GridSign.Models.Entities.WorkflowRecipientSignedDocument", b =>
                {
                    b.HasOne("GridSign.Models.Entities.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("GridSign.Models.Entities.WorkflowSignatureProof", b =>
                {
                    b.HasOne("GridSign.Models.Entities.FileResource", "File")
                        .WithMany("SignatureProofs")
                        .HasForeignKey("FileResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GridSign.Models.Entities.WorkflowRecipientSignature", "RecipientSignature")
                        .WithMany()
                        .HasForeignKey("SignatureProofId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("RecipientSignature");
                });

            modelBuilder.Entity("GridSign.Models.Entities.Field", b =>
                {
                    b.Navigation("RecipientFields");
                });

            modelBuilder.Entity("GridSign.Models.Entities.FileResource", b =>
                {
                    b.Navigation("SignatureProofs");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("GridSign.Models.Entities.Template", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("GridSign.Models.Entities.TemplateDocument", b =>
                {
                    b.Navigation("TemplateDocumentFiles");

                    b.Navigation("TemplateRecipients");
                });

            modelBuilder.Entity("GridSign.Models.Entities.TemplateRecipient", b =>
                {
                    b.Navigation("TemplateRecipientField");
                });

            modelBuilder.Entity("GridSign.Models.Entities.Workflow", b =>
                {
                    b.Navigation("WorkflowEnvelopes");
                });

            modelBuilder.Entity("GridSign.Models.Entities.WorkflowEnvelope", b =>
                {
                    b.Navigation("WorkflowRecipient");
                });

            modelBuilder.Entity("GridSign.Models.Entities.WorkflowRecipient", b =>
                {
                    b.Navigation("RecipientSignatures");
                });

            modelBuilder.Entity("GridSign.Models.Entities.WorkflowRecipientSignedDocument", b =>
                {
                    b.Navigation("Signatures");

                    b.Navigation("SignedDocumentVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
